version: '3.8'

services:
  app:
    build: 
      context: ../node
      dockerfile: Dockerfile
    container_name: app
    networks:
      - node-network
    volumes:
      - ../node:/usr/src/app
    tty: true
    ports:
        - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql/mysql-server:8.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  node-network:
    driver: bridge
